namespace OkPlayer.Core;

/// <summary>
/// Where installed builds look for updates. The feed is a static Velopack channel manifest
/// (releases.&lt;channel&gt;.json) served from GitHub Pages — a stable HTTPS URL that no amount of
/// GitHub release-list churn can bury (issue #131; GithubSource only ever saw the first 10 entries
/// of the release listing, so 10 releases without the feed asset blinded the whole fleet). The
/// manifest's asset entries carry absolute URLs pointing back at GitHub release assets, so the
/// packages themselves stay on GitHub Releases; only discovery moved.
/// The feed is regenerated by .github/workflows/publish-win-feed.yml on every published Windows
/// release — the base URL below must match that workflow's output layout.
/// </summary>
public static class UpdateFeed
{
    /// <summary>Base URL of the Windows update channel. Velopack appends
    /// "releases.{channel}.json" to this, so it must end with a slash.</summary>
    public const string WinBaseUrl = "https://befeast.github.io/ok-player/updates/win/";

    /// <summary>The Velopack channel name, pinned on both sides: `vpk pack --channel win` on the
    /// publish side and ExplicitChannel on the client, so a platform-default change in a future
    /// Velopack can never silently fork the two.</summary>
    public const string WinChannel = "win";
}
