#!/usr/bin/env bash
# Build the signed APT repository served from the static GitHub Pages site (issues #683, #689),
# so Debian/Ubuntu users receive OK Player updates through their own system updater.
#
# Output layout (served at https://befeast.github.io/ok-player/apt/):
#   apt/ok-player-archive-keyring.asc          armored public signing key (users may keep .asc)
#   apt/ok-player-archive-keyring.gpg          the same key dearmored, for /usr/share/keyrings
#   apt/ok-player.sources                      ready-made deb822 stanza for the stable suite
#   apt/ok-player-candidate.sources            the same for the candidate (QA) suite
#   apt/pool/main/o/ok-player/*.deb            the packages themselves, shared by both suites
#   apt/dists/<suite>/Release                  the archive index
#   apt/dists/<suite>/{InRelease,Release.gpg}  the OpenPGP signatures over it
#   apt/dists/<suite>/main/binary-amd64/{Packages,Packages.gz,Release}
#
# Two suites, one archive:
#
#   * stable    — built from the published linux-v* releases. What a normal user subscribes to.
#   * candidate — built from the rolling `linux-candidate` release, whose current build is named
#                 by its candidate.linux.json pointer (the same pointer the .deb self-updater and
#                 the AppImage lane read). This is the QA channel: testers get the rolling build
#                 through apt instead of downloading .deb files by hand (issue #689).
#
# The two suites are generated by one code path and signed by one key. They share pool/: a
# package that appears in both is stored once and referenced twice, and the rolling-window
# budget charges its bytes once. `stable` and `candidate` are separate suites, so a machine
# subscribed to one is never offered the other's builds — that separation is the point, and it
# is why the candidate suite is emphatically not a way to make `stable` newer.
#
# Derived, never authored — the same rule build-win-feed.sh and build-linux-feed.sh follow.
# The published GitHub releases are the source of truth, so this script is a pure function of
# them plus the signing key. It never reads the previously deployed site, because GitHub Pages
# replaces the site atomically:
#
#   * Additive. A new build only ever adds a pool file and a Packages paragraph. Older retained
#     versions keep the exact bytes, and therefore the exact Size/SHA256, they had in the
#     previous run — a release can never rewrite the checksum of a version already installed on
#     someone's machine.
#   * Idempotent. Re-running over an unchanged release set reproduces the repository content
#     byte for byte: pool contents come from immutable release assets, the Packages ordering
#     is dpkg-scanpackages' stable ordering, Packages.gz is written with `gzip -n`, and each
#     suite's Release Date is taken from its newest retained build's publication timestamp
#     rather than from the clock. The detached OpenPGP signatures are deliberately NOT
#     byte-stable: every signature carries its own creation time, and dating a signature from
#     an old release just to make bytes repeat would be a lie about when it was made.
#   * Bounded. GitHub Pages publishes at most ~1 GB per site, and Linux packages that bundle
#     libmpv are ~76-85 MB each, so the archive is a rolling window. Each suite keeps its own
#     newest N builds (OKP_APT_MAX_VERSIONS for stable, OKP_APT_CANDIDATE_MAX_VERSIONS for
#     candidate) and both draw on one shared OKP_APT_POOL_BUDGET_BYTES pool budget, charged per
#     distinct pool file. After each suite's current build is reserved, the remaining budget is
#     offered to the two tails in turn, so neither suite can starve the other. Dropping a tail
#     entry removes the pool file and its Packages paragraph together, so the archive never
#     carries a dangling reference; versions outside the window stay downloadable from their
#     GitHub release, which is what the .deb self-updater already uses.
#
# The signing key is fetched at run time from Infisical (never a GitHub Actions secret, never
# an artifact) into an ephemeral GNUPGHOME that is destroyed on exit including on failure, the
# imported key's fingerprint is compared against the expected one before anything is signed,
# and a missing or unreadable secret aborts the lane. Publishing an unsigned or
# unexpectedly-signed archive is worse than publishing nothing: apt would either refuse it or,
# worse, trust it.
#
# Usage: build-apt-repo.sh <owner/repo> <output-dir>
# Requires: gh (authenticated; GH_TOKEN in CI), jq, curl, gpg, dpkg-scanpackages (dpkg-dev),
#           gzip, sha256sum, md5sum.
# Requires in the environment: INFISICAL_CLIENT_ID, INFISICAL_CLIENT_SECRET.
set -euo pipefail

# --- Archive identity -----------------------------------------------------------------
OKP_APT_ORIGIN='OK Player'
OKP_APT_LABEL='OK Player'
OKP_APT_STABLE_SUITE='stable'
OKP_APT_CANDIDATE_SUITE='candidate'
OKP_APT_COMPONENT='main'
OKP_APT_ARCH='amd64'
OKP_APT_POOL_SUBDIR='pool/main/o/ok-player'
OKP_APT_KEYRING_BASENAME='ok-player-archive-keyring'

# The rolling candidate release and the pointer asset that names its current build. The pointer
# is the single source of truth for "which candidate is live" (okp-core::candidate_build writes
# it last, after the artifacts it names are uploaded), so the candidate suite advertises exactly
# what the candidate feed advertises — never a half-published build.
OKP_APT_CANDIDATE_TAG="${OKP_APT_CANDIDATE_TAG:-linux-candidate}"
OKP_APT_CANDIDATE_POINTER='candidate.linux.json'

# --- Rolling-window bounds (see the header) -------------------------------------------
OKP_APT_MAX_VERSIONS="${OKP_APT_MAX_VERSIONS:-10}"
# The pointer carries the current build plus okp-core's MAX_RETAINED_PREVIOUS (5) predecessors,
# so 6 is "everything the candidate feed still names". Setting it to 0 disables the candidate
# suite entirely, which is the supported way to publish stable-only.
OKP_APT_CANDIDATE_MAX_VERSIONS="${OKP_APT_CANDIDATE_MAX_VERSIONS:-6}"
OKP_APT_POOL_BUDGET_BYTES="${OKP_APT_POOL_BUDGET_BYTES:-$((900 * 1024 * 1024))}"

# --- Infisical coordinates ------------------------------------------------------------
# These are NOT secrets (issue #683) and belong in the workflow surface; only the two client
# credentials come from GitHub Actions secrets.
OKP_APT_INFISICAL_API='https://secrets.oklabs.uk/api'
OKP_APT_INFISICAL_PROJECT='5b5038c7-46d5-496f-bfa6-6184cb41e143'
OKP_APT_INFISICAL_ENVIRONMENT='prod'
OKP_APT_INFISICAL_SECRET_PATH='/ok-player'

# The real stdout, saved before anything can capture it. ::add-mask:: only takes effect when
# GitHub Actions actually sees it, and every masked value is produced inside a command
# substitution whose stdout belongs to the caller — so masks are written here instead.
exec {OKP_APT_LOG_FD}>&1

okp_apt_fail() {
  printf '::error::%s\n' "$*" >&2
  exit 1
}

okp_apt_secret_reference() {
  printf 'services/%s%s:%s' \
    "$OKP_APT_INFISICAL_ENVIRONMENT" "$OKP_APT_INFISICAL_SECRET_PATH" "$1"
}

okp_apt_require_tools() {
  local tool
  for tool in "$@"; do
    command -v "$tool" >/dev/null 2>&1 \
      || okp_apt_fail "the APT repository lane requires ${tool}, which is not on PATH."
  done
}

# --- Infisical ------------------------------------------------------------------------
# The access token and the secret values never appear in a command line: curl reads the
# request from a --config stanza on stdin, so nothing sensitive lands in the process table
# of a shared runner. Failure bodies are never echoed either, because an auth response can
# carry a token.
OKP_APT_INFISICAL_TOKEN=''

okp_apt_infisical_login() {
  local client_id="${INFISICAL_CLIENT_ID:-}" client_secret="${INFISICAL_CLIENT_SECRET:-}"
  [[ -n "$client_id" ]] \
    || okp_apt_fail "INFISICAL_CLIENT_ID is empty; the APT lane cannot read $(okp_apt_secret_reference gpg-private-key) and refuses to publish an unsigned repository."
  [[ -n "$client_secret" ]] \
    || okp_apt_fail "INFISICAL_CLIENT_SECRET is empty; the APT lane cannot read $(okp_apt_secret_reference gpg-private-key) and refuses to publish an unsigned repository."

  local body status token
  body="$(mktemp)"
  status="$(
    jq -nc --arg clientId "$client_id" --arg clientSecret "$client_secret" \
      '{clientId: $clientId, clientSecret: $clientSecret}' \
      | curl --config <(
          printf 'silent\nshow-error\nrequest = "POST"\nurl = "%s"\nheader = "Content-Type: application/json"\ndata-binary = "@-"\noutput = "%s"\nwrite-out = "%%{http_code}"\nmax-time = 30\n' \
            "${OKP_APT_INFISICAL_API}/v1/auth/universal-auth/login" "$body"
        )
  )" || { rm -f "$body"; okp_apt_fail "Infisical universal-auth login to ${OKP_APT_INFISICAL_API} failed at the transport level."; }
  if [[ "$status" != 200 ]]; then
    rm -f "$body"
    okp_apt_fail "Infisical universal-auth login to ${OKP_APT_INFISICAL_API} returned HTTP ${status}; the APT lane cannot read $(okp_apt_secret_reference gpg-private-key)."
  fi
  token="$(jq -r '.accessToken // empty' <"$body")"
  rm -f "$body"
  [[ -n "$token" ]] \
    || okp_apt_fail "Infisical universal-auth login to ${OKP_APT_INFISICAL_API} returned no accessToken."
  okp_apt_mask "$token"
  OKP_APT_INFISICAL_TOKEN="$token"
}

# Hide a value from GitHub Actions logs. ::add-mask:: is line-oriented, so an armored key is
# masked line by line; the directive itself is only emitted under Actions, where it is not
# echoed back.
okp_apt_mask() {
  [[ -n "${GITHUB_ACTIONS:-}" ]] || return 0
  local line
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    printf '::add-mask::%s\n' "$line" >&"$OKP_APT_LOG_FD"
  done <<<"$1"
}

# The production secret reader: prints one secret value on stdout, non-zero on any failure.
# main() pins this into okp_apt_build_signed_repo; the tests pin a stub in its place, so the
# "which secret is missing" message below is produced by the same production code path in
# both cases.
okp_apt_infisical_secret() {
  local name="$1" body status value
  [[ -n "$OKP_APT_INFISICAL_TOKEN" ]] || okp_apt_infisical_login
  body="$(mktemp)"
  status="$(
    curl --config <(
      printf 'silent\nshow-error\nurl = "%s"\nheader = "Authorization: Bearer %s"\noutput = "%s"\nwrite-out = "%%{http_code}"\nmax-time = 30\n' \
        "${OKP_APT_INFISICAL_API}/v3/secrets/raw/${name}?workspaceId=${OKP_APT_INFISICAL_PROJECT}&environment=${OKP_APT_INFISICAL_ENVIRONMENT}&secretPath=$(okp_apt_urlencode "$OKP_APT_INFISICAL_SECRET_PATH")" \
        "$OKP_APT_INFISICAL_TOKEN" "$body"
    )
  )" || { rm -f "$body"; return 1; }
  if [[ "$status" != 200 ]]; then
    printf 'Infisical returned HTTP %s for %s\n' "$status" "$(okp_apt_secret_reference "$name")" >&2
    rm -f "$body"
    return 1
  fi
  value="$(jq -r '.secret.secretValue // empty' <"$body")"
  rm -f "$body"
  [[ -n "$value" ]] || return 1
  okp_apt_mask "$value"
  printf '%s' "$value"
}

okp_apt_urlencode() {
  local string="$1" out='' index char
  for ((index = 0; index < ${#string}; index++)); do
    char="${string:index:1}"
    case "$char" in
      [a-zA-Z0-9._~-]) out+="$char" ;;
      *) out+="$(printf '%%%02X' "'$char")" ;;
    esac
  done
  printf '%s' "$out"
}

# Read one required secret into a file, or abort naming exactly which secret is missing.
# Deliberately not a command substitution at the call site: an abort has to end the lane,
# not just a subshell.
okp_apt_require_secret() {
  local reader="$1" name="$2" destination="$3" value
  if ! value="$("$reader" "$name")" || [[ -z "$value" ]]; then
    okp_apt_fail "cannot read $(okp_apt_secret_reference "$name"); the APT lane refuses to publish an unsigned repository."
  fi
  printf '%s\n' "$value" >"$destination"
  chmod 600 "$destination"
}

# --- Ephemeral GNUPGHOME --------------------------------------------------------------
# One cleanup handler for the whole script: the signing home and the download staging
# directory are registered in globals rather than in competing traps, so entering the signed
# build can never disarm the staging cleanup (or the other way round). It runs on success, on
# failure, and on a signal.
OKP_APT_GNUPGHOME=''
OKP_APT_STAGING=''

okp_apt_cleanup() {
  okp_apt_destroy_gnupghome "$OKP_APT_GNUPGHOME"
  OKP_APT_GNUPGHOME=''
  if [[ -n "$OKP_APT_STAGING" ]]; then
    rm -rf -- "$OKP_APT_STAGING"
    OKP_APT_STAGING=''
  fi
}

okp_apt_make_gnupghome() {
  local base="${RUNNER_TEMP:-${TMPDIR:-/tmp}}"
  local home
  home="$(mktemp -d "${base%/}/okp-apt-gnupg.XXXXXXXX")"
  chmod 700 "$home"
  printf '%s' "$home"
}

okp_apt_destroy_gnupghome() {
  local home="${1:-}"
  [[ -n "$home" && -d "$home" ]] || return 0
  GNUPGHOME="$home" gpgconf --kill all >/dev/null 2>&1 || true
  rm -rf -- "$home"
}

okp_apt_normalize_fingerprint() {
  printf '%s' "${1//[[:space:]]/}" | tr '[:lower:]' '[:upper:]'
}

# Import the private key and prove it is the intended one. Only public listings are read —
# there is no --list-secret-keys style dump anywhere in this script.
okp_apt_import_signing_key() {
  local home="$1" key_file="$2" expected_file="$3" imported expected
  GNUPGHOME="$home" gpg --batch --quiet --no-tty --import "$key_file" >/dev/null 2>&1 \
    || okp_apt_fail "the value of $(okp_apt_secret_reference gpg-private-key) is not an importable OpenPGP key."
  imported="$(
    GNUPGHOME="$home" gpg --batch --no-tty --with-colons --fingerprint --list-keys 2>/dev/null \
      | awk -F: '$1 == "fpr" { print $10; exit }'
  )"
  imported="$(okp_apt_normalize_fingerprint "$imported")"
  expected="$(okp_apt_normalize_fingerprint "$(cat "$expected_file")")"
  [[ -n "$imported" ]] \
    || okp_apt_fail "no OpenPGP key was imported from $(okp_apt_secret_reference gpg-private-key)."
  [[ -n "$expected" ]] \
    || okp_apt_fail "$(okp_apt_secret_reference gpg-fingerprint) is empty; the imported signing key cannot be verified."
  if [[ "$imported" != "$expected" ]]; then
    okp_apt_fail "signing key fingerprint mismatch: imported ${imported}, but $(okp_apt_secret_reference gpg-fingerprint) expects ${expected}. Refusing to sign the APT repository with an unexpected key."
  fi
  printf '%s' "$imported"
}

# --- Repository generation (pure) -----------------------------------------------------
# Turn a directory of .deb files plus an archive plan into a complete unsigned archive under
# <repo-root>. The plan is a directory:
#
#   <plan>/suites             suite names, one per line, in publication order
#   <plan>/<suite>.members    pool basenames the suite indexes, one per line
#   <plan>/<suite>.epoch      the Unix timestamp that dates the suite's Release file
#
# Everything the output depends on is therefore an input, which is what makes a rerun
# reproducible.
okp_apt_generate_repo() {
  local staging="$1" repo_root="$2" plan="$3"
  local pool="${repo_root}/${OKP_APT_POOL_SUBDIR}"

  local packages=()
  local deb
  while IFS= read -r -d '' deb; do packages+=("$deb"); done \
    < <(find "$staging" -maxdepth 1 -name '*.deb' -type f -print0 | sort -z)
  ((${#packages[@]} > 0)) \
    || okp_apt_fail "no .deb reached the APT staging directory; refusing to publish an empty archive."

  local suites=()
  [[ -s "${plan}/suites" ]] \
    || okp_apt_fail "the archive plan names no suite; refusing to publish an APT repository with no dists/."
  mapfile -t suites < <(grep -v '^[[:space:]]*$' "${plan}/suites")
  ((${#suites[@]} > 0)) \
    || okp_apt_fail "the archive plan names no suite; refusing to publish an APT repository with no dists/."

  rm -rf -- "${repo_root}/dists" "${repo_root}/pool"
  mkdir -p "$pool"
  for deb in "${packages[@]}"; do
    cp -- "$deb" "${pool}/$(basename -- "$deb")"
  done

  # The pool is indexed ONCE, and every suite's Packages is a subset of that one index. That is
  # what makes "stored once, referenced twice" true down to the byte: a package carried by both
  # suites has literally the same paragraph, produced by the same scan, in both indices.
  #
  # An explicit override file pins Section/Priority and keeps dpkg-scanpackages from warning
  # about every package on every run.
  local override diagnostics index
  override="$(mktemp)"
  diagnostics="$(mktemp)"
  index="$(mktemp)"
  printf 'ok-player optional video\n' >"$override"
  if ! (
    cd "$repo_root"
    LC_ALL=C dpkg-scanpackages --multiversion "$OKP_APT_POOL_SUBDIR" "$override"
  ) >"$index" 2>"$diagnostics"; then
    cat "$diagnostics" >&2
    rm -f "$override" "$diagnostics" "$index"
    okp_apt_fail "dpkg-scanpackages could not index the APT pool."
  fi
  rm -f "$override" "$diagnostics"
  if [[ ! -s "$index" ]]; then
    rm -f "$index"
    okp_apt_fail "the generated Packages index is empty; refusing to publish an archive apt cannot resolve."
  fi

  local suite
  for suite in "${suites[@]}"; do
    okp_apt_write_suite "$repo_root" "$suite" "$index" "${plan}/${suite}.members" "${plan}/${suite}.epoch"
  done
  rm -f "$index"

  okp_apt_assert_pool_is_referenced "$repo_root" "${suites[@]}"
}

# Emit the paragraphs of <index> whose Filename is listed in <wanted>, preserving their exact
# bytes and their separators. When every paragraph is wanted the output is the input.
okp_apt_select_paragraphs() {
  local index="$1" wanted="$2"
  awk -v wanted_file="$wanted" '
    BEGIN {
      while ((getline line < wanted_file) > 0) { if (line != "") keep[line] = 1 }
    }
    {
      buffer = buffer $0 "\n"
      if ($0 ~ /^Filename: /) { filename = substr($0, 11) }
      if ($0 == "") {
        if (filename in keep) printf "%s", buffer
        buffer = ""
        filename = ""
      }
    }
    END { if (buffer != "" && (filename in keep)) printf "%s", buffer }
  ' "$index"
}

okp_apt_suite_description() {
  case "$1" in
    "$OKP_APT_CANDIDATE_SUITE")
      printf 'OK Player rolling QA candidate Debian packages (%s)' "$OKP_APT_ARCH" ;;
    *)
      printf 'OK Player Debian packages (%s)' "$OKP_APT_ARCH" ;;
  esac
}

okp_apt_write_suite() {
  local repo_root="$1" suite="$2" index="$3" members="$4" epoch_file="$5"
  local dist="${repo_root}/dists/${suite}"
  local binary_dir="${dist}/${OKP_APT_COMPONENT}/binary-${OKP_APT_ARCH}"

  [[ -s "$members" ]] \
    || okp_apt_fail "the ${suite} suite would carry no package; refusing to publish an empty suite."
  [[ -s "$epoch_file" ]] \
    || okp_apt_fail "the ${suite} suite has no Release date; refusing to date it from the clock."
  local epoch
  epoch="$(cat "$epoch_file")"

  mkdir -p "$binary_dir"

  local wanted name expected=0
  wanted="$(mktemp)"
  while IFS= read -r name; do
    [[ -n "$name" ]] || continue
    [[ -f "${repo_root}/${OKP_APT_POOL_SUBDIR}/${name}" ]] \
      || okp_apt_fail "the ${suite} suite references ${name}, which is not in the pool; refusing to publish an index apt cannot resolve."
    printf '%s/%s\n' "$OKP_APT_POOL_SUBDIR" "$name"
    expected=$((expected + 1))
  done <"$members" >"$wanted"

  okp_apt_select_paragraphs "$index" "$wanted" >"${binary_dir}/Packages"
  rm -f "$wanted"

  local indexed_count
  indexed_count="$(grep -c '^Filename: ' "${binary_dir}/Packages" || true)"
  [[ "$indexed_count" == "$expected" ]] \
    || okp_apt_fail "the ${suite} suite planned ${expected} package(s) but its index carries ${indexed_count}; refusing to publish a suite that does not match its plan."

  # -n: no timestamp or original name in the gzip header, so the byte stream repeats.
  gzip -9nc "${binary_dir}/Packages" >"${binary_dir}/Packages.gz"

  {
    printf 'Archive: %s\n' "$suite"
    printf 'Component: %s\n' "$OKP_APT_COMPONENT"
    printf 'Origin: %s\n' "$OKP_APT_ORIGIN"
    printf 'Label: %s\n' "$OKP_APT_LABEL"
    printf 'Architecture: %s\n' "$OKP_APT_ARCH"
  } >"${binary_dir}/Release"

  local indexed=(
    "${OKP_APT_COMPONENT}/binary-${OKP_APT_ARCH}/Packages"
    "${OKP_APT_COMPONENT}/binary-${OKP_APT_ARCH}/Packages.gz"
    "${OKP_APT_COMPONENT}/binary-${OKP_APT_ARCH}/Release"
  )
  {
    printf 'Origin: %s\n' "$OKP_APT_ORIGIN"
    printf 'Label: %s\n' "$OKP_APT_LABEL"
    printf 'Suite: %s\n' "$suite"
    printf 'Codename: %s\n' "$suite"
    printf 'Architectures: %s\n' "$OKP_APT_ARCH"
    printf 'Components: %s\n' "$OKP_APT_COMPONENT"
    printf 'Date: %s\n' "$(LC_ALL=C date -u -d "@${epoch}" '+%a, %d %b %Y %H:%M:%S UTC')"
    # No Valid-Until on purpose. It would bound a freeze/rollback attack, but it also makes apt
    # reject the archive outright once it lapses — and OK Player releases on no schedule, so any
    # window short enough to be worth having is short enough to strand every user during a quiet
    # month. The archive is served over HTTPS from GitHub Pages and regenerated on every deploy;
    # revisit this if the release cadence ever becomes predictable.
    printf 'Acquire-By-Hash: no\n'
    printf 'Description: %s\n' "$(okp_apt_suite_description "$suite")"
    printf 'MD5Sum:\n'
    okp_apt_checksum_block "$dist" md5sum "${indexed[@]}"
    printf 'SHA256:\n'
    okp_apt_checksum_block "$dist" sha256sum "${indexed[@]}"
  } >"${dist}/Release"
}

# A pool file no suite indexes is dead weight against the byte budget and invisible to apt.
# It can only come from a planning bug, so it fails the lane rather than shipping quietly.
okp_apt_assert_pool_is_referenced() {
  local repo_root="$1"
  shift
  local pool="${repo_root}/${OKP_APT_POOL_SUBDIR}"
  local referenced suite path name
  referenced="$(mktemp)"
  for suite in "$@"; do
    awk '/^Filename: / { print $2 }' \
      "${repo_root}/dists/${suite}/${OKP_APT_COMPONENT}/binary-${OKP_APT_ARCH}/Packages"
  done | sort -u >"$referenced"
  for path in "$pool"/*.deb; do
    [[ -e "$path" ]] || continue
    name="$(basename -- "$path")"
    grep -Fxq "${OKP_APT_POOL_SUBDIR}/${name}" "$referenced" \
      || { rm -f "$referenced"; okp_apt_fail "the pool carries ${name}, which no suite indexes; refusing to publish bytes no client can reach."; }
  done
  rm -f "$referenced"
}

okp_apt_checksum_block() {
  local dist="$1" algorithm="$2"
  shift 2
  local relative size digest
  for relative in "$@"; do
    size="$(stat -c '%s' "${dist}/${relative}")"
    digest="$("$algorithm" "${dist}/${relative}" | cut -d' ' -f1)"
    printf ' %s %16s %s\n' "$digest" "$size" "$relative"
  done
}

# --- Signing --------------------------------------------------------------------------
# The passphrase arrives on file descriptor 3 from a here-string: bash materializes it
# without forking a process, so it never appears in argv or in the process table. Every suite
# is signed by the same key in the same loop — there is no second signing path to keep honest.
okp_apt_sign_repo() {
  local repo_root="$1" home="$2" fingerprint="$3" passphrase="$4"
  shift 4
  local suite dist
  for suite in "$@"; do
    dist="${repo_root}/dists/${suite}"
    GNUPGHOME="$home" gpg --batch --yes --no-tty --pinentry-mode loopback --passphrase-fd 3 \
      --local-user "$fingerprint" --digest-algo SHA512 --armor --detach-sign \
      --output "${dist}/Release.gpg" "${dist}/Release" 3<<<"$passphrase" \
      || okp_apt_fail "detached signing of the ${suite} Release file failed."
    GNUPGHOME="$home" gpg --batch --yes --no-tty --pinentry-mode loopback --passphrase-fd 3 \
      --local-user "$fingerprint" --digest-algo SHA512 --clearsign \
      --output "${dist}/InRelease" "${dist}/Release" 3<<<"$passphrase" \
      || okp_apt_fail "inline signing of the ${suite} InRelease file failed."
  done
}

# --- Client-facing material -----------------------------------------------------------
# One stanza per suite, and deliberately one FILE per suite: subscribing to the QA channel has
# to be a separate, deliberate act, and dropping ok-player.sources into sources.list.d must
# never silently enrol a machine in candidate builds.
okp_apt_write_sources_stanza() {
  local destination="$1" base_url="$2" suite="$3"
  {
    printf 'Types: deb\n'
    printf 'URIs: %s\n' "$base_url"
    printf 'Suites: %s\n' "$suite"
    printf 'Components: %s\n' "$OKP_APT_COMPONENT"
    printf 'Architectures: %s\n' "$OKP_APT_ARCH"
    printf 'Signed-By: /usr/share/keyrings/%s.gpg\n' "$OKP_APT_KEYRING_BASENAME"
  } >"$destination"
}

okp_apt_write_client_material() {
  local repo_root="$1" home="$2" public_key_file="$3" base_url="$4"
  shift 4
  cp -- "$public_key_file" "${repo_root}/${OKP_APT_KEYRING_BASENAME}.asc"
  chmod 644 "${repo_root}/${OKP_APT_KEYRING_BASENAME}.asc"
  GNUPGHOME="$home" gpg --batch --yes --no-tty --dearmor \
    --output "${repo_root}/${OKP_APT_KEYRING_BASENAME}.gpg" \
    <"${repo_root}/${OKP_APT_KEYRING_BASENAME}.asc" \
    || okp_apt_fail "the value of $(okp_apt_secret_reference gpg-public-key) is not an armored OpenPGP key."
  chmod 644 "${repo_root}/${OKP_APT_KEYRING_BASENAME}.gpg"

  rm -f "${repo_root}/ok-player.sources" "${repo_root}/ok-player-candidate.sources"
  local suite
  for suite in "$@"; do
    case "$suite" in
      "$OKP_APT_CANDIDATE_SUITE")
        okp_apt_write_sources_stanza "${repo_root}/ok-player-candidate.sources" "$base_url" "$suite" ;;
      "$OKP_APT_STABLE_SUITE")
        okp_apt_write_sources_stanza "${repo_root}/ok-player.sources" "$base_url" "$suite" ;;
    esac
  done
}

# --- The whole signed build, with the secret source as a parameter ---------------------
# Everything that can abort the lane — a missing secret, an unexpected fingerprint — runs
# here, so the tests exercise the production control flow rather than a copy of it.
okp_apt_build_signed_repo() {
  local staging="$1" repo_root="$2" plan="$3" base_url="$4" reader="$5"
  local home
  home="$(okp_apt_make_gnupghome)"
  OKP_APT_GNUPGHOME="$home"
  trap okp_apt_cleanup EXIT INT TERM

  okp_apt_require_secret "$reader" gpg-private-key "${home}/signing-key.asc"
  okp_apt_require_secret "$reader" gpg-public-key "${home}/public-key.asc"
  okp_apt_require_secret "$reader" gpg-fingerprint "${home}/fingerprint"
  okp_apt_require_secret "$reader" gpg-passphrase "${home}/passphrase"

  local fingerprint
  fingerprint="$(okp_apt_import_signing_key "$home" "${home}/signing-key.asc" "${home}/fingerprint")"
  printf 'APT archive will be signed by %s\n' "$fingerprint"

  local suites=()
  mapfile -t suites < <(grep -v '^[[:space:]]*$' "${plan}/suites")

  okp_apt_generate_repo "$staging" "$repo_root" "$plan"
  okp_apt_sign_repo "$repo_root" "$home" "$fingerprint" "$(cat "${home}/passphrase")" "${suites[@]}"
  okp_apt_write_client_material "$repo_root" "$home" "${home}/public-key.asc" "$base_url" "${suites[@]}"

  okp_apt_destroy_gnupghome "$home"
  OKP_APT_GNUPGHOME=''
}

# --- Build discovery ------------------------------------------------------------------
# Both fetchers emit the same row shape, newest first:
#
#   <published>\t<label>\t<pool basename>\t<size in bytes>
#
# <published> dates the suite's Release file (only the first retained row is used), <label>
# names the thing in log messages and, for stable, is the release tag the .deb is downloaded
# from.
okp_apt_fetch_stable_rows() {
  local repo="$1" out="$2"
  if ! gh api --paginate "repos/${repo}/releases?per_page=100" \
    --jq '.[] | select((.draft | not) and .published_at != null)
              | select(.tag_name | test("^linux-v"))
              | . as $release
              | .assets[]
              | select(.name | test("^ok-player_.*_amd64\\.deb$"))
              | [ $release.published_at, $release.tag_name, .name, .size ] | @tsv' \
    | sort -r >"$out"; then
    okp_apt_fail "could not list the published releases of ${repo}."
  fi
  [[ -s "$out" ]] \
    || okp_apt_fail "no published linux-v* release carries an ok-player_*_amd64.deb; refusing to build an APT repository from nothing (issue #683)."
}

# The rolling candidate. Its identity comes from candidate.linux.json — the pointer okp-core
# uploads last, after the artifacts it names — so the candidate suite can never advertise a
# build the candidate feed does not. Sizes come from the release assets themselves, because
# those are the bytes that will actually be downloaded.
#
# An absent rolling release is not a failure: before the first candidate publish, or with
# OKP_APT_CANDIDATE_MAX_VERSIONS=0, the archive is simply stable-only.
okp_apt_fetch_candidate_rows() {
  local repo="$1" work="$2" out="$3"
  : >"$out"

  if ((OKP_APT_CANDIDATE_MAX_VERSIONS < 1)); then
    printf 'APT candidate: OKP_APT_CANDIDATE_MAX_VERSIONS is 0; publishing the %s suite only.\n' \
      "$OKP_APT_STABLE_SUITE" >&2
    return 0
  fi

  local assets="${work}/candidate-assets.json"
  if ! gh api "repos/${repo}/releases/tags/${OKP_APT_CANDIDATE_TAG}" \
       --jq '[.assets[] | {name: .name, size: .size}]' >"$assets" 2>/dev/null; then
    printf 'APT candidate: no %s release in %s; publishing the %s suite only.\n' \
      "$OKP_APT_CANDIDATE_TAG" "$repo" "$OKP_APT_STABLE_SUITE" >&2
    return 0
  fi
  if ! jq -e --arg name "$OKP_APT_CANDIDATE_POINTER" 'any(.[]; .name == $name)' >/dev/null <"$assets"; then
    printf 'APT candidate: %s carries no %s pointer; publishing the %s suite only.\n' \
      "$OKP_APT_CANDIDATE_TAG" "$OKP_APT_CANDIDATE_POINTER" "$OKP_APT_STABLE_SUITE" >&2
    return 0
  fi

  gh release download "$OKP_APT_CANDIDATE_TAG" --repo "$repo" --dir "$work" \
    --pattern "$OKP_APT_CANDIDATE_POINTER" --clobber \
    || okp_apt_fail "could not download ${OKP_APT_CANDIDATE_POINTER} from ${OKP_APT_CANDIDATE_TAG}; refusing to guess which candidate is live."

  okp_apt_candidate_rows_from_pointer "${work}/${OKP_APT_CANDIDATE_POINTER}" "$assets" "$out"
}

# Split out so the pointer -> rows translation is testable without GitHub.
okp_apt_candidate_rows_from_pointer() {
  local pointer="$1" assets="$2" out="$3"
  : >"$out"
  local published version name size current=1
  while IFS=$'\t' read -r published version name size; do
    [[ -n "$name" ]] || continue
    if [[ -z "$size" || "$size" == "null" ]]; then
      ((current == 0)) \
        || okp_apt_fail "the rolling candidate ${version} names ${name}, which is not attached to the ${OKP_APT_CANDIDATE_TAG} release; refusing to publish a candidate suite that disagrees with the candidate feed."
      printf 'APT candidate: %s is no longer attached to %s; dropping it from the %s suite.\n' \
        "$name" "$OKP_APT_CANDIDATE_TAG" "$OKP_APT_CANDIDATE_SUITE" >&2
      continue
    fi
    printf '%s\t%s\t%s\t%s\n' "$published" "$version" "$name" "$size" >>"$out"
    current=0
  done < <(
    jq -r --slurpfile assets "$assets" '
      ($assets[0] | map({key: .name, value: .size}) | from_entries) as $size
      | .timestamp_utc as $published
      | ([{version: .version, name: .package.name}]
         + [.history[] | {version: .version, name: .package.name}])
      | map(select(.name != null and .name != ""))
      | .[]
      | [$published, .version, .name, ($size[.name] // "")] | @tsv
    ' "$pointer"
  )
  [[ -s "$out" ]] \
    || okp_apt_fail "${OKP_APT_CANDIDATE_POINTER} names no Debian package; refusing to publish a candidate suite from nothing."
}

# --- Rolling window planning ----------------------------------------------------------
# The budget is charged per distinct pool file, so a package carried by both suites costs its
# bytes once. Each suite's current build is reserved first and is not optional: a signed
# archive advertising an older version than the update feeds do is worse than no publish at
# all, because apt clients would accept it. The remaining budget is then offered to the two
# tails in turn, so a long stable history cannot starve the candidate suite or the other way
# round.
OKP_APT_PLAN_TOTAL=0
declare -A OKP_APT_PLAN_CHARGED=()
declare -A OKP_APT_PLAN_KEPT=()
declare -A OKP_APT_PLAN_SEEN=()

okp_apt_plan_reset() {
  OKP_APT_PLAN_TOTAL=0
  OKP_APT_PLAN_CHARGED=()
  OKP_APT_PLAN_KEPT=()
  OKP_APT_PLAN_SEEN=()
}

# okp_apt_plan_take <suite> <cap> <mandatory> <out> <row>
# Returns 0 when the row was retained, 1 when it was skipped. A mandatory row that cannot be
# retained aborts the lane instead.
okp_apt_plan_take() {
  local suite="$1" cap="$2" mandatory="$3" out="$4" row="$5"
  local published label filename size
  IFS=$'\t' read -r published label filename size <<<"$row"
  [[ -n "$filename" && -n "$size" ]] || return 1
  [[ -z "${OKP_APT_PLAN_SEEN[${suite}:${filename}]:-}" ]] || return 1

  local kept="${OKP_APT_PLAN_KEPT[$suite]:-0}"
  if ((kept >= cap)); then
    ((mandatory == 0)) \
      || okp_apt_fail "the ${suite} window is ${cap} build(s), so the archive cannot carry the current ${label}; refusing to publish a ${suite} suite without it."
    printf 'APT window: %s is outside the newest %s %s build(s); still downloadable from its GitHub release.\n' \
      "$label" "$cap" "$suite" >&2
    return 1
  fi

  local cost=0
  [[ -n "${OKP_APT_PLAN_CHARGED[$filename]:-}" ]] || cost="$size"
  if ((OKP_APT_PLAN_TOTAL + cost > OKP_APT_POOL_BUDGET_BYTES)); then
    ((mandatory == 0)) \
      || okp_apt_fail "the current ${suite} build ${label} needs ${cost} bytes, which does not fit the ${OKP_APT_POOL_BUDGET_BYTES}-byte APT pool budget; refusing to publish an archive that would advertise an older version than the update feeds do."
    printf 'APT window: %s does not fit the %s-byte pool budget; still downloadable from its GitHub release.\n' \
      "$label" "$OKP_APT_POOL_BUDGET_BYTES" >&2
    return 1
  fi

  OKP_APT_PLAN_TOTAL=$((OKP_APT_PLAN_TOTAL + cost))
  OKP_APT_PLAN_CHARGED[$filename]=1
  OKP_APT_PLAN_KEPT[$suite]=$((kept + 1))
  OKP_APT_PLAN_SEEN[${suite}:${filename}]=1
  printf '%s\n' "$row" >>"$out"
  return 0
}

# okp_apt_plan_suites <stable rows> <candidate rows> <stable out> <candidate out>
# Writes the retained rows of each suite, newest first. The candidate outputs stay empty when
# there is no rolling candidate, which is how a stable-only archive is described.
okp_apt_plan_suites() {
  local stable_rows="$1" candidate_rows="$2" stable_out="$3" candidate_out="$4"
  local stable=() candidate=()
  [[ -s "$stable_rows" ]] \
    || okp_apt_fail "the rolling window was given no ${OKP_APT_STABLE_SUITE} build; refusing to publish an empty APT repository."
  mapfile -t stable < <(grep -v '^[[:space:]]*$' "$stable_rows" || true)
  if [[ -s "$candidate_rows" ]]; then
    mapfile -t candidate < <(grep -v '^[[:space:]]*$' "$candidate_rows" || true)
  fi
  ((${#stable[@]} > 0)) \
    || okp_apt_fail "the rolling window was given no ${OKP_APT_STABLE_SUITE} build; refusing to publish an empty APT repository."

  okp_apt_plan_reset
  : >"$stable_out"
  : >"$candidate_out"

  okp_apt_plan_take "$OKP_APT_STABLE_SUITE" "$OKP_APT_MAX_VERSIONS" 1 "$stable_out" "${stable[0]}" \
    || okp_apt_fail "the current ${OKP_APT_STABLE_SUITE} row is malformed: ${stable[0]}"
  if ((${#candidate[@]} > 0)); then
    okp_apt_plan_take "$OKP_APT_CANDIDATE_SUITE" "$OKP_APT_CANDIDATE_MAX_VERSIONS" 1 \
      "$candidate_out" "${candidate[0]}" \
      || okp_apt_fail "the current ${OKP_APT_CANDIDATE_SUITE} row is malformed: ${candidate[0]}"
  fi

  local index=1
  while ((index < ${#stable[@]} || index < ${#candidate[@]})); do
    if ((index < ${#stable[@]})); then
      okp_apt_plan_take "$OKP_APT_STABLE_SUITE" "$OKP_APT_MAX_VERSIONS" 0 \
        "$stable_out" "${stable[index]}" || true
    fi
    if ((index < ${#candidate[@]})); then
      okp_apt_plan_take "$OKP_APT_CANDIDATE_SUITE" "$OKP_APT_CANDIDATE_MAX_VERSIONS" 0 \
        "$candidate_out" "${candidate[index]}" || true
    fi
    index=$((index + 1))
  done
}

# --- Staging ---------------------------------------------------------------------------
# Downloads land in a per-suite directory and are merged into one pool staging directory, so a
# package both suites carry is downloaded and stored once. A name collision whose bytes differ
# is a hard failure: the two suites would otherwise advertise the same Filename with different
# content, and exactly one of them would be lying.
okp_apt_merge_into_pool() {
  local source="$1" pool_staging="$2" suite="$3" path name
  for path in "$source"/*.deb; do
    [[ -e "$path" ]] || continue
    name="$(basename -- "$path")"
    if [[ -e "${pool_staging}/${name}" ]]; then
      cmp -s -- "$path" "${pool_staging}/${name}" \
        || okp_apt_fail "the ${suite} suite carries a different ${name} than another suite already staged; refusing to publish two packages under one Filename."
      rm -f -- "$path"
    else
      mv -- "$path" "${pool_staging}/${name}"
    fi
  done
}

okp_apt_stage_stable() {
  local repo="$1" selected="$2" download_dir="$3" pool_staging="$4" epoch_file="$5"
  local published tag name size newest=''
  mkdir -p "$download_dir"
  while IFS=$'\t' read -r published tag name size; do
    [[ -n "$tag" ]] || continue
    [[ -n "$newest" ]] || newest="$published"
    if [[ -e "${pool_staging}/${name}" ]]; then continue; fi
    gh release download "$tag" --repo "$repo" --dir "$download_dir" \
      --pattern "$name" --clobber \
      || okp_apt_fail "could not download ${name} from ${tag}."
  done <"$selected"
  okp_apt_merge_into_pool "$download_dir" "$pool_staging" "$OKP_APT_STABLE_SUITE"
  [[ -n "$newest" ]] || okp_apt_fail "the ${OKP_APT_STABLE_SUITE} suite retained no release."
  date -u -d "$newest" '+%s' >"$epoch_file"
}

okp_apt_stage_candidate() {
  local repo="$1" selected="$2" download_dir="$3" pool_staging="$4" epoch_file="$5"
  local published version name size newest=''
  mkdir -p "$download_dir"
  while IFS=$'\t' read -r published version name size; do
    [[ -n "$name" ]] || continue
    [[ -n "$newest" ]] || newest="$published"
    if [[ -e "${pool_staging}/${name}" ]]; then continue; fi
    gh release download "$OKP_APT_CANDIDATE_TAG" --repo "$repo" --dir "$download_dir" \
      --pattern "$name" --clobber \
      || okp_apt_fail "could not download ${name} from ${OKP_APT_CANDIDATE_TAG}."
  done <"$selected"
  okp_apt_merge_into_pool "$download_dir" "$pool_staging" "$OKP_APT_CANDIDATE_SUITE"
  [[ -n "$newest" ]] || okp_apt_fail "the ${OKP_APT_CANDIDATE_SUITE} suite retained no build."
  date -u -d "$newest" '+%s' >"$epoch_file"
}

okp_apt_report_suite() {
  local repo_root="$1" suite="$2"
  printf 'APT suite %s:\n' "$suite"
  awk '/^Package:/ { package = $2 } /^Version:/ { printf "  %s %s\n", package, $2 }' \
    "${repo_root}/dists/${suite}/${OKP_APT_COMPONENT}/binary-${OKP_APT_ARCH}/Packages"
}

main() {
  local repo="${1:?usage: build-apt-repo.sh <owner/repo> <output-dir>}"
  local out="${2:?usage: build-apt-repo.sh <owner/repo> <output-dir>}"

  okp_apt_require_tools gh jq curl gpg gpgconf dpkg-scanpackages gzip sha256sum md5sum stat cmp

  # Authenticate before spending minutes on downloads: a lane that cannot reach the signing
  # key must fail immediately, not after building an archive it is not allowed to sign.
  okp_apt_infisical_login

  local work
  work="$(mktemp -d)"
  OKP_APT_STAGING="$work"
  trap okp_apt_cleanup EXIT INT TERM

  local plan="${work}/plan" pool_staging="${work}/pool"
  mkdir -p "$plan" "$pool_staging"

  okp_apt_fetch_stable_rows "$repo" "${work}/stable.rows"
  okp_apt_fetch_candidate_rows "$repo" "$work" "${work}/candidate.rows"
  okp_apt_plan_suites "${work}/stable.rows" "${work}/candidate.rows" \
    "${plan}/${OKP_APT_STABLE_SUITE}.selected" "${plan}/${OKP_APT_CANDIDATE_SUITE}.selected"

  local suites=("$OKP_APT_STABLE_SUITE")
  if [[ -s "${plan}/${OKP_APT_CANDIDATE_SUITE}.selected" ]]; then
    suites+=("$OKP_APT_CANDIDATE_SUITE")
  fi
  printf '%s\n' "${suites[@]}" >"${plan}/suites"

  okp_apt_stage_stable "$repo" "${plan}/${OKP_APT_STABLE_SUITE}.selected" \
    "${work}/download-${OKP_APT_STABLE_SUITE}" "$pool_staging" \
    "${plan}/${OKP_APT_STABLE_SUITE}.epoch"
  cut -f3 "${plan}/${OKP_APT_STABLE_SUITE}.selected" >"${plan}/${OKP_APT_STABLE_SUITE}.members"

  if [[ -s "${plan}/${OKP_APT_CANDIDATE_SUITE}.selected" ]]; then
    okp_apt_stage_candidate "$repo" "${plan}/${OKP_APT_CANDIDATE_SUITE}.selected" \
      "${work}/download-${OKP_APT_CANDIDATE_SUITE}" "$pool_staging" \
      "${plan}/${OKP_APT_CANDIDATE_SUITE}.epoch"
    cut -f3 "${plan}/${OKP_APT_CANDIDATE_SUITE}.selected" \
      >"${plan}/${OKP_APT_CANDIDATE_SUITE}.members"
  fi

  local owner="${repo%%/*}" name="${repo##*/}"
  local base_url="https://${owner,,}.github.io/${name}/apt"
  local repo_root="${out}/apt"
  mkdir -p "$repo_root"
  # Idempotent, and also staged by the two feed builders — but this script has to stand on its
  # own: without it a Jekyll pass could rewrite or hide archive files, and apt would be served
  # something other than what was signed.
  touch "${out}/.nojekyll"

  okp_apt_build_signed_repo "$pool_staging" "$repo_root" "$plan" "$base_url" okp_apt_infisical_secret

  printf 'APT archive built at %s (pool: %s bytes over %s file(s)) from:\n' \
    "$base_url" "$OKP_APT_PLAN_TOTAL" "${#OKP_APT_PLAN_CHARGED[@]}"
  local suite
  for suite in "${suites[@]}"; do
    okp_apt_report_suite "$repo_root" "$suite"
  done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
